### ISSUE TITLE
tmux-fzf second level menus do not work with fish shell

### ISSUE THREAD

**Issue by maksyms** [sainnhe/tmux-fzf#26] opened 2020-11-24 18:51 UTC
It seems that the second level menus in `tmux-fzf` do not work.

Using:

- fish, version 3.1.2
- tmux 2.6
- fzf 0.24.3 (722d66e), from Github

I get to select the first level of menu fine using the shortcut:

![image](https://user-images.githubusercontent.com/595059/100138216-962d2080-2e85-11eb-9ba8-ea903c02c2b0.png)

But then, when pressing on any menu option, the screen blinks and nothing happens.

The fix seems to be quite simple: delete `.fzf-tmux` from `tmux-fzf/scripts` and create a symbolic link `.fzf-tmux` instead, pointing to `$HOME/.fzf/bin/fzf-tmux`. Once done, everything works fine.

**Comment by sainnhe** [comment] 2020-11-25 00:41
This is not the case, `.fzf-tmux` is a modified version of built-in `fzf-tmux`, it supports some extra options and popup menus.

Maybe we need some debug, sorry but I don't have much time recently.

**Comment by maksyms** [comment] 2020-11-25 08:42
Hm, ok, I'll have a look at what the differences are in more details. Is there a reason not to submit your `fzf-tmux` changes to the upstream `fzf` at all?

**Comment by sainnhe** [comment] 2020-11-25 10:37
When I first created this repository, there is a bug in fzf that `fzf-tmux` can't be launched by `tmux run-shell`. I searched for this bug in the issue page of fzf and found someone provided a fix, but the author didn't merge it, so I decided to maintain my own fork. But looks like this bug has been fixed in the upstream now.

I also added some new features for `.fzf-tmux`, the most important one is the support for popup window. If the upstream adds the support for it, then it will be OK to switch to the upstream.

If you have time, you can try to open a PR in the repository of fzf that adds support for popup window.

**Comment by sainnhe** [comment] 2020-12-29 13:01
Sorry for late reply, I just tried this, but cannot reproduce. I'm using arch linux.

I noticed that your tmux remains in 2.6, maybe you can try to update tmux, I'd recommend you to compile tmux from master branch so you can get the latest feature.

**Comment by teklabania** [comment] 2020-12-30 07:33
Hi, I have exactly the same problem as @maksyms. I'm running Manjaro with:
- fish 3.1.2-2
- tmux 3.1_c-1
- fish 3.1.2-2

**Comment by maksyms** [comment] 2020-12-31 12:48
I've just tried again, here are more detailed observations:

1. WSL, Ubuntu 20.04, `zsh` as the default shell: everything seems to work
2. WSL, Ubuntu 20.04, `fish` as the default shell: breaks. I get an error message for a split second. I recorded it with my camera and found the right frame. The error I can see says:

> fish: Expected a variable name after this $.
> env TERM=screen-256color FZF_DEFAULT_OPTS=$'--cycle --layo

3. WSL, Ubuntu 20.04, `fish` launched from `zsh`, which is the default shell: all seems to work.

So it looks like the issue is definitely to do with fish being the default shell.

**Comment by sainnhe** [comment] 2021-01-01 10:39
I see, it will only reproduce when using fish && $FZF_DEFAULT_OPTS exists. I'll try to fix it later.

**Comment by sainnhe** [comment] 2021-01-01 12:47
I noticed that the latest version of `fzf-tmux` has added support for popup window, so I'm going to use the original one directly.

This bug should be fixed via https://github.com/sainnhe/tmux-fzf/commit/aea34d64df15a817d77c3ab4c7c80af939562afa, you can update this plugin and get it a try. @maksyms @teklabania

**Comment by maksyms** [comment] 2021-01-01 17:05
I've just updated the plugin (`prefix` + `U` in [TPM](https://github.com/tmux-plugins/tpm), and the head is at c85ee1e right now. The plugin broke even for `zsh` as the default shell. Grabbing the error is really difficult, but recording on iPhone and then watching frame by frame reveals:
`invalid preview window option: follow`

And also, there is a lot of screen blinking. So it doesn't work now I'm afraid.

**Comment by maksyms** [comment] 2021-01-01 17:16
Just confirmed that reverting to 312685b, which my original PR was based on, addresses this latest issue. So the bug must be in one of the commits after that one.

**Comment by sainnhe** [comment] 2021-01-01 22:38
I guess it's because your fzf version is too old. Try to update fzf and see if this bug has been fixed.

**Comment by maksyms** [comment] 2021-01-01 23:18
I'm using the latest `fzf` available from the github repo:

![image](https://user-images.githubusercontent.com/595059/103447766-6d1f5d00-4c87-11eb-8274-9479b55ba27e.png)

Aren't you pulling in the `fzf` version into your repo anyway?

**Comment by maksyms** [comment] 2021-01-01 23:26
Ah. I actually did the proper update - and everything is ok now, thank you.

I'll now test it with `fish` as the default shell.

**Comment by maksyms** [comment] 2021-01-01 23:33
@sainnhe I can confirm that after updating `fzf` to version 0.24.4 and updating `tmux-fzf` to the latest version, everything works correctly, including when the default shell is `fish`. So this bug can be closed now from my perspective. Thank you!

**Comment by sainnhe** [comment] 2021-01-02 01:45
Version detection has been added via https://github.com/sainnhe/tmux-fzf/commit/fd86ff9045a093fa19a71d5b0e6112822b74f868, so `:follow` option will not be enabled in fzf < 0.24.4 .

Closed.

**Closed by sainnhe** 2021-01-02 01:45 UTC
Labels: bug
